<?php

namespace AppBundle\Entity;

/**
 * RecipeIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
